{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c18f91c9-2697-4625-8b8c-d60562a42e12",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import time\n",
    "from sqlalchemy import create_engine\n",
    "import logging\n",
    "from ingestion_db import ingest_db  # Custom function to ingest DataFrame into database\n",
    "import numpy as np\n",
    "\n",
    "# ----------------------------\n",
    "# Create SQLAlchemy engine\n",
    "# ----------------------------\n",
    "# This establishes a connection to the MySQL database using SQLAlchemy.\n",
    "# Replace \"root\", \"Mohammed313\", \"localhost\", \"3306\", and \"inventory\" with your credentials.\n",
    "engine = create_engine(\"mysql+pymysql://root:Mohammed313@localhost:3306/inventory\")\n",
    "\n",
    "# ----------------------------\n",
    "# Configure logging\n",
    "# ----------------------------\n",
    "# Logs will be written to the file 'logs/Vendor_Summary_GET.log'.\n",
    "# Levels: DEBUG (lowest), INFO, WARNING, ERROR, CRITICAL\n",
    "logging.basicConfig(\n",
    "    filename=\"logs/Vendor_Summary_GET.log\",\n",
    "    filemode=\"a\",  # 'a' appends logs, 'w' would overwrite\n",
    "    level=logging.DEBUG,\n",
    "    format=\"%(asctime)s - %(levelname)s - %(message)s\"\n",
    ")\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# Function: create_vendor_summary\n",
    "# ----------------------------\n",
    "def create_vendor_summary(conn):\n",
    "    \"\"\"\n",
    "    Fetches and merges purchase, sales, and vendor invoice data to create a \n",
    "    consolidated vendor summary.\n",
    "    \n",
    "    Parameters:\n",
    "        conn : SQLAlchemy connection object\n",
    "    Returns:\n",
    "        pandas.DataFrame : merged vendor summary\n",
    "    \"\"\"\n",
    "    \n",
    "    # SQL query explanation:\n",
    "    # 1. Subquery 'ps': Aggregates purchase data by VendorNumber, VendorName, Brand, and Description\n",
    "    #    - MAX(PurchasePrice) and MAX(Volume) ensures the highest price/volume is used\n",
    "    #    - SUM(Quantity) and SUM(Dollars) gives totals for each product/vendor\n",
    "    # 2. Subquery 'ss': Aggregates sales data by VendorNo and Brand\n",
    "    #    - Calculates total sales dollars, sales quantity, sales price, and excise tax\n",
    "    # 3. Subquery 'fs': Aggregates freight costs from vendor invoices\n",
    "    # 4. Joins: Purchase summary is LEFT JOINED with sales and freight data\n",
    "    # 5. Result is ordered by TotalPurchaseDollars descending\n",
    "    \n",
    "    query = \"\"\"\n",
    "    SELECT\n",
    "        ps.VendorNumber,\n",
    "        ps.VendorName,\n",
    "        ps.Brand,\n",
    "        ps.Description,\n",
    "        ps.PurchasePrice,\n",
    "        ps.ActualPrice,\n",
    "        ps.Volume,\n",
    "        ps.TotalPurchaseQuantity,\n",
    "        ps.TotalPurchaseDollars,\n",
    "        ss.TotalSalesQuantity,\n",
    "        ss.TotalSalesDollars,\n",
    "        ss.TotalSalesPrice,\n",
    "        ss.TotalExciseTax,\n",
    "        fs.FreightCost\n",
    "    FROM (\n",
    "        SELECT \n",
    "            p.VendorNumber,\n",
    "            p.VendorName,\n",
    "            p.Brand,\n",
    "            p.Description,\n",
    "            MAX(p.PurchasePrice) AS PurchasePrice,\n",
    "            MAX(pp.Volume) AS Volume,\n",
    "            MAX(pp.Price) AS ActualPrice,\n",
    "            SUM(p.Quantity) AS TotalPurchaseQuantity,\n",
    "            SUM(p.Dollars) AS TotalPurchaseDollars\n",
    "        FROM purchases p\n",
    "        JOIN purchase_prices pp ON p.Brand = pp.Brand\n",
    "        WHERE p.PurchasePrice > 0\n",
    "        GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description\n",
    "    ) AS ps\n",
    "    LEFT JOIN (\n",
    "        SELECT \n",
    "            VendorNo,\n",
    "            Brand,\n",
    "            SUM(SalesDollars) AS TotalSalesDollars,\n",
    "            SUM(SalesPrice) AS TotalSalesPrice,\n",
    "            SUM(SalesQuantity) AS TotalSalesQuantity,\n",
    "            SUM(ExciseTax) AS TotalExciseTax\n",
    "        FROM sales\n",
    "        GROUP BY VendorNo, Brand\n",
    "    ) AS ss\n",
    "    ON ps.VendorNumber = ss.VendorNo AND ps.Brand = ss.Brand\n",
    "    LEFT JOIN (\n",
    "        SELECT VendorNumber, SUM(Freight) AS FreightCost\n",
    "        FROM vendor_invoice\n",
    "        GROUP BY VendorNumber\n",
    "    ) AS fs\n",
    "    ON ps.VendorNumber = fs.VendorNumber\n",
    "    ORDER BY ps.TotalPurchaseDollars DESC;\n",
    "    \"\"\"\n",
    "    \n",
    "    # Execute the query and return a pandas DataFrame\n",
    "    return pd.read_sql_query(query, conn)\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# Function: clean_data\n",
    "# ----------------------------\n",
    "def clean_data(df):\n",
    "    \"\"\"\n",
    "    Cleans and enriches the vendor summary DataFrame by:\n",
    "    - Converting data types\n",
    "    - Filling missing values\n",
    "    - Stripping whitespace\n",
    "    - Adding calculated columns like GrossProfit, ProfitMargin, etc.\n",
    "    \n",
    "    Parameters:\n",
    "        df : pandas.DataFrame\n",
    "    Returns:\n",
    "        pandas.DataFrame : cleaned and enriched DataFrame\n",
    "    \"\"\"\n",
    "    \n",
    "    # Convert 'Volume' column to float for numerical calculations\n",
    "    df[\"Volume\"] = df[\"Volume\"].astype(float)\n",
    "\n",
    "    # Fill all missing values with 0 to avoid calculation errors\n",
    "    df.fillna(0, inplace=True)\n",
    "\n",
    "    # Remove leading/trailing whitespaces from strings\n",
    "    df[\"VendorName\"] = df[\"VendorName\"].str.strip()\n",
    "    df[\"Description\"] = df[\"Description\"].str.strip()\n",
    "\n",
    "    # Add calculated columns\n",
    "    df[\"GrossProfit\"] = df[\"TotalSalesDollars\"] - df[\"TotalPurchaseDollars\"]\n",
    "    df[\"ProfitMargin\"] = np.where(df[\"TotalSalesDollars\"] != 0,\n",
    "                                  (df[\"GrossProfit\"] / df[\"TotalSalesDollars\"]) * 100, 0)\n",
    "    df[\"StockTurnover\"] = np.where(df[\"TotalPurchaseQuantity\"] != 0,\n",
    "                                   df[\"TotalSalesQuantity\"] / df[\"TotalPurchaseQuantity\"], 0)\n",
    "    df[\"SalestoPurchaseRatio\"] = np.where(df[\"TotalPurchaseDollars\"] != 0,\n",
    "                                          df[\"TotalSalesDollars\"] / df[\"TotalPurchaseDollars\"], 0)\n",
    "\n",
    "    # Replace infinite values (from division by zero) with 0\n",
    "    df.replace([np.inf, -np.inf], 0, inplace=True)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ----------------------------\n",
    "# Main script execution\n",
    "# ----------------------------\n",
    "if __name__ == \"__main__\":\n",
    "    # Connect to the database using SQLAlchemy engine\n",
    "    with engine.connect() as conn:\n",
    "        logging.info(\"Creating Vendor Summary Table...\")\n",
    "        \n",
    "        # Create the vendor summary DataFrame\n",
    "        summary_df = create_vendor_summary(conn)\n",
    "        logging.info(f\"Summary head:\\n{summary_df.head()}\")  # Log first few rows\n",
    "\n",
    "        logging.info(\"Cleaning Data...\")\n",
    "        # Clean and enrich the data\n",
    "        clean_df = clean_data(summary_df)\n",
    "        logging.info(f\"Cleaned head:\\n{clean_df.head()}\")  # Log first few rows\n",
    "\n",
    "        logging.info(\"Ingesting data into DB...\")\n",
    "        # Insert the cleaned DataFrame into the database\n",
    "        ingest_db(clean_df, \"vendor_sales_summary\", engine)  # Ensure correct function name\n",
    "        logging.info(\"Data ingestion completed.\")\n",
    "        \n",
    "Print('Successfully Done')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e2dc75d-b503-46c1-9b9d-8020ca437f9e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
